### ISSUE TITLE
Could you add some way to use Together.ai models?

### ISSUE THREAD

**Issue by Cristofer543** [msveshnikov/allchat#17]
Example some of the models of together.ai DBRX-intruc and etc.

**Comment by msveshnikov** [comment]
Sure, it is definitely possible. Hopefully today evening

**Comment by Cristofer543** [comment]
> Sure, it is definitely possible. Hopefully today evening

entiendo me avisas

**Comment by msveshnikov** [comment]
Done. Please press Ctrl-F5 and find model selector in My Account

**Comment by Cristofer543** [comment]
> Done. Press Ctrl-F5 and look for the model selector in My Account.

You could create a discord channel to be able to talk there to have more good conversations and not having to be opening the github,

if you want I can provide you my together.io api for you to use it in the webs and you could improve more the stability of the webs that some response are very slow.

**Comment by msveshnikov** [comment]
I have my own Together key, no problem. You can put yours in My account btw

**Comment by Cristofer543** [comment]
> I have my own Together key, no problem. You can put yours in My account btw

Hi bro a question because the site is a bit slow and the answers take a long time to appear ?

**Comment by msveshnikov** [comment]
Switch to Mixtral7x8 or DBRX they are instant (2-3 seconds)

**Comment by msveshnikov** [comment]
Also maybe start New Chat. Median interact time:
![image](https://github.com/msveshnikov/allchat/assets/8682996/ccc03e72-af95-4d20-9d74-5f97d8368b41)
