### ISSUE TITLE
You could add these new functions

### ISSUE THREAD

**Issue by Cristofer543** [msveshnikov/allchat#19]
You could add a way to regenerate the answer like chatgpt claude and etc and you can edit the messages.

**Comment by msveshnikov** [comment]
No prob, just sent your suggestion to allchat itself and got this code, will add later 
![Screenshot_2024-04-13-14-31-02-551_com android chrome](https://github.com/msveshnikov/allchat/assets/8682996/3ad7b2d6-45c0-4bef-96e2-7ea6d07b1b1e)

**Comment by Cristofer543** [comment]
> No prob, just sent your suggestion to allchat itself and got this code, will add later !

Entiendo, Oye bro podrias crear un Grupo de discord, y podrias chekear las ia y agregar algo como esto 
![image](https://github.com/msveshnikov/allchat/assets/152051773/e93b2ff0-84b4-4f07-a8ad-a90bdc6a4dad)
lo de la imagen que diga cual modelo ia estas usando y si ese modelo ia se le ppuede enviar imagenes archivo etc o no porque algunos no tienen esa capacidad y aun asi esto le aparece 
![image](https://github.com/msveshnikov/allchat/assets/152051773/56fd79fe-d78f-403e-9d95-9094205d7446)

**Comment by Cristofer543** [comment]
> No prob, just sent your suggestion to allchat itself and got this code, will add later !

I understand, hey bro you could create a discord group, and you could check the ia and add something like this ![image](https://github.com/msveshnikov/allchat/assets/152051773/e93b2ff0-84b4-4f07-a8ad-a90bdc6a4dad) the image thing that says which model ia you are using and if that model ia you can send images file etc or not because some don't have that capability and still this appears ![image](https://github.com/msveshnikov/allchat/assets/152051773/56fd79fe-d78f-403e-9d95-9094205d7446)

**Comment by msveshnikov** [comment]
Understood, but all models accept PDFs, Words, etc (because this is just binary-> text pre-enrichment) so this icon should be visible always

**Comment by msveshnikov** [comment]
https://discord.com/invite/JTk2fHtv

**Comment by msveshnikov** [comment]
Done
