### ISSUE TITLE
install

### ISSUE THREAD

**Issue by tanlentboy** [msveshnikov/allchat#20]
Hello sir, can you get a detailed docker installation configuration tutorial? I tried to install as instructed, but it didn't work!

**Comment by tanlentboy** [comment]
the  allchat-backend  docker:

root@Docker:~# curl localhost:6000
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>

**Comment by msveshnikov** [comment]
Hey there, GET / route doesn't exist in backend, try other like http://localhost:6000/get?file=1.txt

**Comment by tanlentboy** [comment]
Hell, Dear Sir,  When I deploy the server, and then on the chat interface, send a message, it shows that I can't connect to the server, is this server a backend server? But the mondb database is connectable and functional.
![image](https://github.com/msveshnikov/allchat/assets/22891617/70ffac17-2007-41f5-a90a-1f5ebc2b147b)

**Comment by msveshnikov** [comment]
Yes, please check CORs settings, maybe browser decline origin, so add localhost:6000 to cors config in backend (like written in Readme)
