### ISSUE TITLE
option to modify geminis safety settings

### ISSUE THREAD

**Issue by nekohacker591** [msveshnikov/allchat#24]
it now supports full safty settings all the way down to none 
can a slider me added akin to the one from ai playground

**Comment by nekohacker591** [comment]
https://ai.google.dev/gemini-api/docs/safety-settings for more info

**Comment by nekohacker591** [comment]
here is some example code


`from google.generativeai.types import HarmCategory, HarmBlockThreshold

model = genai.GenerativeModel(model_name='gemini-pro-vision')
response = model.generate_content(
    ['Do these look store-bought or homemade?', img],
    safety_settings={
        HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
        HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
    }
)`

**Comment by msveshnikov** [comment]
I would love to do it, but it doesn't work anymore without prepaid $3500 contract with Google.
