### ISSUE TITLE
support for other multamodilities...?

### ISSUE THREAD

**Issue by theone2277** [msveshnikov/allchat#7]
can you add videos support by using ffmpeg to split frames and also support for other pdf, word documents or files?

**Comment by theone2277** [comment]
wanna say, i really appreciate you for sharing the code for images!

**Comment by msveshnikov** [comment]
Sure this is on my plans. By the way PDFs and Word documents are allowed for upload

**Comment by msveshnikov** [comment]
Ok, update from my side: No need in ffmpeg and frame extraction as Files API already has video mime type upload and it works perfectly in AI Studio.  I added mp4 upload to FE & BE but still get 400 from API. Investigating

**Comment by theone2277** [comment]
hello again, can you share any example link for video that i can test? also how to make it work for tinyurl links?

**Comment by msveshnikov** [comment]
Last Update from Google: https://ai.google.dev/tutorials/prompting_with_media/?utm_source=gais&utm_medium=email&utm_campaign=geminipp

So video.mp4 will NOT be supported by API. Splitting by ffmpeg is in progress

**Comment by msveshnikov** [comment]
Implemented, sorry for delay (I was in Lisbon 🥇 )
